#FREE CONTAINER 
FROM ubuntu:latest
RUN apt update -y
RUN apt install nginx -y
RUN rm /var/www/html/index.nginx-debian.html
COPY ./index.html /var/www/html/
EXPOSE 80
ENTRYPOINT [ "nginx" ]
CMD ["-g", "daemon off;"]
